### PR TITLE
Journal week 4

### PR DESCRIPTION
**Pull request by nickycadavillo**

### CODE REVIEW

**Comment by boshnivolo** [comment]
Great tutorial! I'm definitely going to reference later! :+1:

**Comment by jeffworley** [comment]
Great start!  I can particularly empathize with your reflective journal and think you have selected a hot topic for your tutorial that we all could benefit from.  Looking forward to seeing these develop as the week progresses. :+1:

**Comment by ericksonk** [comment]
Journal looks good so far! I think last week was rough for everyone. Small note- I believe the field trip was Wednesday not Tues.

Your tutorial is clear and has well thought-out steps! :+1:

**Comment by rosalsm** [comment]
Good Start Nicky, very positive!! :+1:

**Comment by jmcreasman** [comment]
Can't wait to see what you come up with for your sass tutorial. I will probably be using it several times

**Comment by jeremyrist** [comment]
:+1:

**Comment by Ricecoder** [comment]
Your journal and tutorial are shaping up nicely! I like how positive you are despite having a rough week. Keep up the good work! :+1:

**Comment by karjac14** [comment]
your journal is looking better! nice to know you enjoy CSS! :+1:

**Pull request merged**
