### PR TITLE
Journal week 2

### PR DESCRIPTION
**Pull request by nickycadavillo**

### CODE REVIEW

**Comment by karjac14** [comment]
Great start there Nicky! its almost complete! :+1:

**Comment by rosalsm** [comment]
Here is my :+1:  for you Nicky. Good job gold star!

**Comment by jmcreasman** [comment]
:+1:  You seem to have a firm handle on how the DOM works. I found it helpful for myself reading your summary on it.

**Comment by ericksonk** [comment]
Good overview! Thanks for the link for MVC info-- I need to read up on that :+1:

**Comment by ericquayson** [comment]
:+1: I liked your journal, Nicky! Good facts on the Js. My only suggestion is to talk about any struggles or breakthroughs. This will be a good reference point to look back once you are finished with the program and see the growth you've achieved by sticking through it.

**Comment by rosalsm** [comment]
Good work Nicky, keep swimming :+1:

**Pull request merged**
